export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAIL = 'REGISTER_FAIL'

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const UPDATE_SERVICES_SUCCESS="UPDATE_SERVICES_SUCCESS";
export const UPDATE_SERVICES_FAIL="UPDATE_SERVICES_FAIL";
export const DELETE_SERVICES="DELETE_SERVICES";
export const FETCH_USERS="FETCH_USERS";
export const SET_ALERT = 'SET_ALERT'
export const REMOVE_ALERT = 'REMOVE_ALERT'
export const LOGIN_FAIL = 'LOGIN_FAIL'

export const LOGOUT = 'LOGOUT';
export const ADD_SERVICES_SUCCESS = 'ADD_SERVICES_SUCCESS';
export const ADD_SERVICES_FAIL = 'ADD_SERVICES_FAIL';
export const ADD_JOBREQUEST_SUCCESS = 'ADD_JOBREQUEST_SUCCESS';
export const ADD_JOBREQUEST_FAIL = 'ADD_JOBREQUEST_FAIL';

export const ADD_APPOINTMENT_SUCCESS='ADD_APPOINTMENT_SUCCESS';
export const ADD_APPOINTMENT_FAIL='ADD_APPOINTMENT_FAIL';


export const UPDATE_APPOINTMENT_FAIL='UPDATE_APPOINTMENT_FAIL';
export const UPDATE_APPOINTMENT_SUCCESS='UPDATE_APPOINTMENT_SUCCESS';

export const FETCH_SERVICES     ='FETCH_SERVICES';

export const FETCH_APOINTMENTS     ='FETCH_APOINTMENTS';
export const FETCH_REQUESTCOMPLETE_JOBS_SELLER     ='FETCH_REQUESTCOMPLETE_JOBS_SELLER';
export const FETCH_COMPLETED_JOBS_SELLER     ='FETCH_COMPLETED_JOBS_SELLER';
export const FETCH_COMPLETED_JOBS_BUYER     ='FETCH_COMPLETED_JOBS_BUYER';
export const FETCH_INCOMPLETED_JOBS_BUYER     ='FETCH_INCOMPLETED_JOBS_BUYER';
export const FETCH_INCOMPLETED_JOBS_SELLER     ='FETCH_INCOMPLETED_JOBS_SELLER';
export const FETCH_REQUESTCOMPLETE_JOBS_BUYER     ='FETCH_REQUESTCOMPLETE_JOBS_BUYER';
export const FETCH_ONGOING_JOBS_SELLER     ='FETCH_ONGOING_JOBS_SELLER';
export const FETCH_ONGOING_JOBS_BUYER     ='FETCH_ONGOING_JOBS_BUYER';
export const FETCH_INCOMING_JOBREQUESTS     ='FETCH_INCOMING_JOBREQUESTS';
export const FETCH_OUTGOING_JOBREQUESTS     ='FETCH_OUTGOING_JOBREQUESTS';
export const UPDATE_PROFILE_SUCCESS     ='UPDATE_PROFILE_SUCcESS';
export const UPDATE_PROFILE_FAIL     ='UPDATE_PROFILE_FAIL';
export const UPDATE_JOB_FAIL     ='UPDATE_JOB_FAIL';
export const UPDATE_JOB_SUCCESS     ='UPDATE_JOB_SUCCESS';
export const UPLOAD_PROFILE_FAIL     ='UPLOAD_PROFILE_FAIL';
export const UPLOAD_PROFILE_SUCCESS     ='UPLOAD_PROFILE_SUCCESS';
export const FETCH_PROFILE     ='UPDATE_PROFILE_FAIL';


export const FETCH_PROVIDERS     ='FETCH_PROVIDERS';
export const ACCEPT_JOBREQUEST_SUCCESS     ='ACCEPT_JOBREQUEST_SUCCESS';
export const REJECT_JOBREQUEST_SUCCESS     ='REJECT_JOBREQUEST_SUCCESS';
export const REJECT_JOBREQUEST_FAIL     ='REJECT_JOBREQUEST_FAIL';
export const ACCEPT_JOBREQUEST_FAIL     ='ACCEPT_JOBREQUEST_FAIL';
export const ADD_NOTIFICATION_SUCCESS     ='ADD_NOTIFICATION_SUCCESS';
export const ADD_NOTIFICATION_FAIL     ='ADD_NOTIFICATION_FAIL';
export const FETCH_NOTIFICATIONS     ='FETCH_NOTIFICATIONS';