export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAIL = 'REGISTER_FAIL'

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const FETCH_SERVCATAGORIES="FETCH_SERVCATAGORIES";
export const FETCH_USERS="FETCH_USERS";
export const SET_ALERT = 'SET_ALERT'
export const REMOVE_ALERT = 'REMOVE_ALERT'
export const LOGIN_FAIL = 'LOGIN_FAIL'

export const LOGOUT = 'LOGOUT';

export const FETCH_LISTINGS='FETCH_LISTINGS';

export const UPDATE_LISTINGS='UPDATE_LISTINGS';

export const FETCH_REGIONS     ='FETCH_REGIONS';
export const UPDATE_PROFILE_SUCCESS     ='UPDATE_PROFILE_SUCcESS';
export const UPDATE_PROFILE_FAIL     ='UPDATE_PROFILE_FAIL';
export const UPLOAD_PROFILE_FAIL     ='UPLOAD_PROFILE_FAIL';
export const UPLOAD_PROFILE_SUCCESS     ='UPLOAD_PROFILE_SUCCESS';
export const FETCH_PROFILE     ='UPDATE_PROFILE_FAIL';


export const FETCH_PROVIDERS     ='FETCH_PROVIDERS';
export const FETCH_WEEKLYVENDORS     ='FETCH_WEEKLYVENDORS';
export const FETCH_BUSINESSADVERTISEMENT     ='FETCH_BUSINESSADVERTISEMENT';